apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
  labels:
    app: order-management
spec:
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 20%
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
      imagePullSecrets:
        - name: github-package
      containers:
        - name: order-management
          image: ghcr.io/ismaelvacco/order-management:latest
          command:
            - sleep
            - "50"
          resources:
            requests:
              cpu: 0.5
              memory: 300Mi
            limits:
              cpu: 1
              memory: 300Mi
          env:
            - name: CONFIG_POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: order-management
                  key: postgres_hostname
            - name: CONFIG_POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: order-management
                  key: postgres_username
            - name: CONFIG_POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: order-management
                  key: postgres_password
            - name: CONFIG_POSTGRES_SSLMODE
              valueFrom:
                configMapKeyRef:
                  name: order-management
                  key: postgres_sslmode
