apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 20%
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      imagePullSecrets:
        - name: github-package
      containers:
        - name: redis
          image: redis:7
          resources:
            requests:
              cpu: 0.5
              memory: 1000Mi
            limits:
              cpu: 1
              memory: 1000Mi
          volumeMounts: []
