apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-signal-engine
  labels:
    app: market-signal-engine
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 20%
  selector:
    matchLabels:
      app: market-signal-engine
  template:
    metadata:
      labels:
        app: market-signal-engine
    spec:
      imagePullSecrets:
        - name: github-package
      containers:
        - name: market-signal-engine
          image: ghcr.io/ismaelvacco/market-signal-engine:latest
          resources:
            requests:
              cpu: 0.5
              memory: 300Mi
            limits:
              cpu: 1
              memory: 300Mi
          volumeMounts: []
