apiVersion: apps/v1
kind: Deployment
metadata:
  name: rule-engine
  labels:
    app: rule-engine
spec:
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 20%
  selector:
    matchLabels:
      app: rule-engine
  template:
    metadata:
      labels:
        app: rule-engine
    spec:
      imagePullSecrets:
        - name: github-package
      containers:
        - name: rule-engine
          image: ghcr.io/ismaelvacco/rule-engine:latest
          resources:
            requests:
              cpu: 0.5
              memory: 300Mi
            limits:
              cpu: 1
              memory: 300Mi
