apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- binance-ingestor
- redis
- market-signal-engine
- data-lake-ingestor
- rule-engine
- order-management

images:
- name: ghcr.io/ismaelvacco/binance
  newTag: sha-389727e
- name: ghcr.io/ismaelvacco/market-signal-engine
  newTag: sha-7d5f857
- name: ghcr.io/ismaelvacco/data-lake-ingestor
  newTag: latest
- name: ghcr.io/ismaelvacco/rule-engine
  newTag: sha-1cbb846
- name: ghcr.io/ismaelvacco/order-management
  newTag: sha-db7a6b1